version: '3'
services:
  mosquitto:
    container_name: mosquitto
    restart: always
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ~/projects/docker/mosquitto/log:/mosquitto/log
      - ~/projects/docker/mosquitto/data:/mosquitto/data
      - ~/projects/docker/mosquitto/passwd_file:/mosquitto/config/passwd_file
      - ~/projects/docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: vividious
      POSTGRES_PASSWORD: devTest1234
    ports:
      - "5432:5432"
    volumes:
      - ~/projects/docker/postgres/data:/var/lib/postgresql
